import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import LeftNavbar from "@/components/LeftNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header />
        <main className="flex bg-slate-100">
          <LeftNavbar />
          {children}
        </main>
      </body>
    </html>
  );
}
